name: Buildpack Registry
on:
    release:
        types:
            - published
jobs:
    register:
        name: Package, Publish, and Register
        runs-on:
            - ubuntu-latest
        steps:
            - id: checkout
              name: Checkout code
              uses: actions/checkout@v2
            - if: ${{ github.event_name != 'pull_request' || ! github.event.pull_request.head.repo.fork }}
              name: Login to GitHub Package Registry
              uses: docker/login-action@v1
              with:
                registry: ghcr.io
                username: ${{ github.repository_owner }}
                password: ${{ secrets.GHCR_TOKEN }}
            - id: pack
              name: Setup Pack CLI
              uses: buildpacks/github-actions/setup-pack@v3.0.0
            - id: package
              name: Package Buildpack
              run: |
                #!/usr/bin/env bash
                set -euo pipefail

                BP_ID="$(cat buildpack.toml | yj -t | jq -r .buildpack.id)"
                BP_VERSION="$(cat buildpack.toml | yj -t | jq -r .buildpack.version)"
                pack package-buildpack --config package.toml --publish ${PACKAGE}:${BP_VERSION}
                DIGEST="$(crane digest ${PACKAGE}:${BP_VERSION})"

                echo "::set-output name=id::$BP_ID"
                echo "::set-output name=version::$BP_VERSION"
                echo "::set-output name=digest::$DIGEST"
              shell: bash
              env:
                PACKAGE: ghcr.io/${{ github.repository_owner }}/buildpacks/jkutner_null
            - id: register
              name: Register Buildpack
              uses: docker://ghcr.io/buildpacks/actions/registry:main
              with:
                token:   ${{ secrets.PUBLIC_REPO_TOKEN }}
                id:      ${{ steps.package.outputs.id }}
                version: ${{ steps.package.outputs.version }}
                address: ghcr.io/jkutner/buildpacks/jkutner_null@${{ steps.package.outputs.digest }}